version: '3'
services:
  audio_features_extraction:
    image: registry.insight-centre.org/annandas-phd/audio-features-extraction:latest
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    volumes:
      - ./raw_files:/app/raw_files
      - ./audio_features_extraction/testing.py:/app/audio_features_extraction/testing.py
      - ./audio_features_extraction/conf.py:/app/audio_features_extraction/conf.py
    working_dir: /app/audio_features_extraction
    entrypoint: /bin/sh -c
